In [2]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

new_temp = temperature + 2

print("Original temperatures:", temperature)
print("Corrected temperatures:", new_temp)

Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures: [27 30 33 37 40 29 35 42]


In [3]:
fahrenheit = (9/5) * new_temp + 32

print("Temperature in Fahrenheit:", fahrenheit)

Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]


In [4]:
above_32 = new_temp[new_temp > 32]

print("Readings greater than 32°C:", above_32)

Readings greater than 32°C: [33 37 40 35 42]


In [5]:
count = np.sum(new_temp > 32)

print("Number of readings above 32°C:", count)

Number of readings above 32°C: 5


In [6]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print(steps)

[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]


In [7]:
print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500


In [8]:
day_total = np.sum(steps, axis=0)

print("Total steps for each day:", day_total)

Total steps for each day: [26500 27300 30400]


In [9]:
user_total = np.sum(steps, axis=1)

print("Total steps for each user:", user_total)

Total steps for each user: [18300 24500 14400 27000]


In [10]:
max_pos = np.unravel_index(np.argmax(steps), steps.shape)

print("Position of maximum steps:", max_pos)
print("Maximum steps:", steps[max_pos])

Position of maximum steps: (np.int64(3), np.int64(2))
Maximum steps: 9500


In [12]:
original = np.array([1, 2, 3, 4, 5, 6])

print("Original:", original)

Original: [1 2 3 4 5 6]


In [13]:
subset = original[1:5]

print("Subset:", subset)

Subset: [2 3 4 5]


In [14]:
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]


In [15]:
copied = original[1:5].copy()

copied[0] = 500

print("Original:", original)
print("Copied array:", copied)

Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]


In [16]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print("First row:", matrix[0])

First row: [1 2 3 4]


In [18]:
print("Last row:", matrix[-1])

Last row: [ 9 10 11 12]


In [19]:
print("Second column:", matrix[:, 1])

Second column: [ 2  6 10]


In [20]:
print(matrix[1:3, 2:4])

[[ 7  8]
 [11 12]]


In [21]:
flat_arr = matrix.flatten()
ravel_arr = matrix.ravel()

print("Using flatten():", flat_arr)
print("Using ravel():", ravel_arr)

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
ravel_arr[0] = 100

print("After modifying ravel:")
print("Original matrix:")
print(matrix)

print("Ravel array:")
print(ravel_arr)

After modifying ravel:
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel array:
[100   2   3   4   5   6   7   8   9  10  11  12]


In [23]:
flat_arr[1] = 200

print("After modifying flatten:")
print("Original matrix:")
print(matrix)

print("Flatten array:")
print(flat_arr)

After modifying flatten:
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten array:
[  1 200   3   4   5   6   7   8   9  10  11  12]


In [25]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [26]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

In [27]:
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

Shape of X: (4, 3)
Dimensions of X: 2


In [28]:
XT = X.T

print("X transpose:")
print(XT)

X transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [29]:
product = X.T @ X

print("X.T @ X:")
print(product)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [30]:
inverse = np.linalg.inv(product)

print("Inverse:")
print(inverse)

Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [31]:
beta = inverse @ X.T @ y

print("Coefficients:")
print(beta)

Coefficients:
[-0.15921454  0.14083853 10.06302242]


In [32]:
new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print("Predicted assistance score:", prediction)

Predicted assistance score: 75.27862544779117
