In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)

print("After adding 2:", arr + 2)

print("After multiplying by 3:", arr * 3)

print("After dividing by 2:", arr / 2)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])

reverse_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reverse_arr)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)

max_value = values[np.argmax(counts)]

print("Most frequent value:", max_value)
print("Indices:", np.where(x == max_value)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_value = values[np.argmax(counts)]

print("Most frequent value:", max_value)
print("Indices:", np.where(y == max_value)[0])

Most frequent value: 1
Indices: [0 1 2]


In [8]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print("1st row, 2nd column:", arr[0,1])

print("3rd row, 1st column:", arr[2,0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [9]:
ucs420_dhruv = np.linspace(10,100,25)

print("Array:")
print(ucs420_dhruv)

print("Dimension:", ucs420_dhruv.ndim)

print("Shape:", ucs420_dhruv.shape)

print("Total Elements:", ucs420_dhruv.size)

print("Data Type:", ucs420_dhruv.dtype)

print("Total Bytes:", ucs420_dhruv.nbytes)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200


In [10]:
transpose_arr = ucs420_dhruv.reshape(5,5)

print("Transpose using reshape:")
print(transpose_arr)

Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


In [11]:
print("Using T attribute:")
print(ucs420_dhruv.T)

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
ucs420_dhruv = np.array([[10,20,30,40],
                         [50,60,70,80],
                         [90,15,20,35]])

print("Original Array:")
print(ucs420_dhruv)

print("Mean:", np.mean(ucs420_dhruv))

print("Median:", np.median(ucs420_dhruv))

print("Maximum:", np.max(ucs420_dhruv))

print("Minimum:", np.min(ucs420_dhruv))

print("Unique Elements:", np.unique(ucs420_dhruv))

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]


In [13]:
reshaped_ucs420_dhruv = ucs420_dhruv.reshape(4,3)

print("Reshaped Array:")
print(reshaped_ucs420_dhruv)

Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [14]:
resized_ucs420_dhruv = np.resize(ucs420_dhruv,(2,3))

print("Resized Array:")
print(resized_ucs420_dhruv)

Resized Array:
[[10 20 30]
 [40 50 60]]
